### ISSUE TITLE
Debug locally - Chrome Debug Tools

### ISSUE THREAD

**Issue by sherif-botros** [VirtoCommerce/vue-starter-theme#52]
Hello :)

Could  you please share some instructions on how to debug this locally?

I have set up the environment per instructions on Read-me file, however when I try to set my own Catalog of Products to this I could not get it to work; the browser goes into infinite loop trying to fetch no-image.svg, but I cannot get a reference to the Code line that is broken, as I could only use `yarn compress` to get the environment to work with my Storefront.  `yarn dev` runs its own server on `localhost:3000`, but I don't know how to use this with Storefront on `localhost:2083`

Must I use a specific Catalog?

Any help or instructions on how to debug the actual VUE code would be great.

Thanks,
Sherif

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7929 has been created

**Comment by DanilBayushev** [comment]
Hello, @sherif-botros .
Could you please describe in more detail the steps of reproducing the problem, as well as the expected and actual results? This will help us to resolve this issue faster.

**Comment by DanilBayushev** [comment]
Answer was posted here: https://www.virtocommerce.org/t/debug-locally-chrome-debug-tools/421
