### ISSUE TITLE
Pictures from readme look so different to the design

### ISSUE THREAD

**Issue by CKGrafico** [VirtoCommerce/vue-starter-theme#6]
Hello, just curious about if I'm doing wrong, I've deployed dev branch and the initial results are really different to your screenshots. Is this ok? I know is only styling but I want to be sure that Im using the correct code

![image](https://user-images.githubusercontent.com/2048511/107640693-f2c4fe00-6c72-11eb-80bd-33c9595a3e48.png)

VS

![image](https://user-images.githubusercontent.com/2048511/107640733-ff495680-6c72-11eb-8865-21eff4feaa75.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6976 has been created

**Comment by CKGrafico** [comment]
Seem because dev branch is inspired in https://www.vuestorefront.io/product because you're using their components, could be?

**Comment by tatarincev** [comment]
We changed the entire theme code, but Read.me has still not changed yet. Hi, I've just fixed it.

We use the https://www.storefrontui.io/ UI vueJS eCommerce sematic component library for this theme.

**Comment by CKGrafico** [comment]
Clarified, thanks the theme is working like a charm my last step is to understand in which part are you using liquid templates and I'll understand everything :)

**Comment by tatarincev** [comment]
If you want we can schedule a quick call, I'll present your the all theme key concepts and it can save a little your time?

**Comment by CKGrafico** [comment]
sounds really good to me you can send me a dm via twitter @CKGrafico :)

**Comment by tatarincev** [comment]
Unfortunately, I don't have a Twitter account, how about https://gitter.im/?

**Comment by CKGrafico** [comment]
Perfect thanks!
